services:
  frontend:
    build: .
    ports:
      - "8080:80"
    environment:
      - API_SECRET=HARDCODED_API_SECRET_FOR_SCAN_TEST
      - DB_PASSWORD=hardcoded_db_password_scan_test
    depends_on:
      - backend

  backend:
    image: node:22-alpine3.21
    command: sh -c "apk update && apk upgrade --no-cache && npx json-server --watch /data/db.json --port 3000 --host 0.0.0.0"
    volumes:
      - ./db.json:/data/db.json
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://admin:PgSecret99@database:5432/annonces
